---
# version: 1.0.2

- hosts: localhost
  become_user: root
  tasks:
     - name: Reset SELinux after installs
       become: yes
       command: restorecon -R -v /dev
       when: (ansible_distribution != "MacOSX") and
             (ansible_os_family != "VMware Photon OS")

