---
# version: 1.0.0
# designed to work with Rocky Linux, not tested on any other Linux distro

- hosts: localhost
  tasks:
     - name: install dependencies
       become: yes
       package:
         name:
           - nginx
         state: latest
       when: ansible_distribution != "MacOSX"
     
     - name: Stop nginx
       become: yes
       service:
         name: nginx
         state: stopped
     
     - name: nginx autoindex
       become: yes
       copy:
         dest: /etc/nginx/default.d/00-autoindex.conf
         content: |
           autoindex on;
     
     - name: nginx follow symlinks
       become: yes
       copy:
         dest: /etc/nginx/conf.d/00-symlinks.conf
         content: |
           disable_symlinks off;

     - name: Permission private key
       become: yes
       file:
         path: "/etc/pki/tls/private/{{ ansible_fqdn }}.key"
         owner: nginx
     
     - name: Enable TLS in Nginx
       become: yes
       copy:
         dest: /etc/nginx/conf.d/00-tls.conf
         content: |
           server {{ '{' }}
             listen       443 ssl http2;
             listen       [::]:443 ssl http2;
             server_name  _;
             root         /usr/share/nginx/html;
             ssl_certificate "/etc/pki/tls/certs/{{ ansible_fqdn }}.crt";
             ssl_certificate_key "/etc/pki/tls/private/{{ ansible_fqdn }}.key";
             ssl_session_cache shared:SSL:1m;
             ssl_session_timeout  10m;
             ssl_ciphers PROFILE=SYSTEM;
             ssl_prefer_server_ciphers on;
             # Load configuration files for the default server block.
             include /etc/nginx/default.d/*.conf;
             error_page 404 /404.html;
                 location = /40x.html {{ '{' }}
             {{ '}' }}
             error_page 500 502 503 504 /50x.html;
                 location = /50x.html {{ '{' }}
             {{ '}' }}
           {{ '}' }}
     
     - name: Enable nginx
       become: yes
       service:
         name: nginx
         state: started
         enabled: yes
     
...
