---
# version: 1.0.1
#
- hosts: localhost
  become_user: root
  tasks:
     - name: install the latest for selinux - RHEL
       become: yes
       package:
         name:
           - policycoreutils-python
           - setroubleshoot-server
         state: latest
       when: ansible_os_family == "RedHat"

     - name: install the latest for selinux - Debian
       become: yes
       package:
         name:
           - policycoreutils
           - selinux-utils
         state: latest
       when: ansible_os_family == "Debian"
...
