---
# version: 1.0.4

- hosts: localhost
  gather_facts: true
  become_user: root
  tasks:
     - name: install system updates for redhat systems
       become: yes
       yum: name=* state=latest update_cache=yes
       when: ansible_os_family == "RedHat"

     - name: install system updates for ubuntu systems
       become: yes
       apt: upgrade=dist update_cache=yes
       when: ansible_os_family == "Debian"

     - name: install the latest ntp and other required dependencies for RHEL < 8
       become: yes
       package:
         name:
           - ntp
           - git
           - python2-pip
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8",'<')

     - name: install the latest ntp and other required dependencies for RHEL >= 8
       become: yes
       package:
         name:
           - chrony
           - git
           - python2-pip
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("7",'>')

     - name: install the other required dependencies Ubuntu
       become: yes
       package:
         name: 
           - ntp
           - git
           - python-pip
         state: latest
       when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version is version("20",'<')) or
             (ansible_distribution == "Debian" and ansible_distribution_major_version is version("10",'<'))

     - name: install the other required dependencies Debian
       become: yes
       package:
         name: 
           - chrony
           - git
           - python3-pip
         state: latest
       when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version is version("19",'>')) or
             (ansible_distribution == "Debian" and ansible_distribution_major_version is version("9",'>'))

     - name: Upgrade PIP
       become: yes
       pip:
         name: pip
         state: latest

     - name: Install pexpect
       become: yes
       pip:
         name: pexpect

     - name: Package Facts
       package_facts:
         manager: "auto"

     - name: Set Facts
       set_fact:
         set_time: ntp
       when: ansible_os_family == "Debian"

     - name: Set Facts
       set_fact:
         set_time: ntpd
       when: ansible_os_family == "RedHat"

     - name: Set Facts
       set_fact:
         set_time: chronyd
       when: '"chrony" in ansible_facts.packages'

     - name: Stop Time Daemon
       become: yes
       service:
         name: "{{set_time}}"
         state: stopped
       when: (aac_base_tz is defined)

     - name: Set timezone
       become: yes
       timezone:
         name: "{{ item }}"
         with_items:
           - "{{ aac_base_tz }}"
       when: aac_base_tz is defined

     - name: Enable Time Daemon
       become: yes
       service:
         name: "{{set_time}}"
         enabled: yes

     - name: Enable Time Daemon
       become: yes
       service:
         name: "{{set_time}}"
         enabled: yes

     - name: Stop postfix
       become: yes
       service:
         name: postfix
         state: stopped
       when: '"postfix" in ansible_facts.packages'
