---
# version: 1.0.2
#
- hosts: localhost
  become_user: root
  tasks:
     - name: install the latest for selinux - RHEL < 8
       become: yes
       package:
         name:
           - policycoreutils-python
           - setroubleshoot-server
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8",'<')

     - name: install the latest for selinux - RHEL >= 8
       become: yes
       package:
         name:
           - python3-policycoreutils
           - setroubleshoot-server
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("7",'>')

     - name: install the latest for selinux - Debian
       become: yes
       package:
         name:
           - policycoreutils
           - selinux-utils
         state: latest
       when: ansible_os_family == "Debian"
...
