---
# version: 1.0.3

- hosts: localhost
  gather_facts: true
  become_user: root
  tasks:
     - name: install system updates for redhat systems
       become: yes
       yum: name=* state=latest update_cache=yes
       when: (ansible_distribution == "Fedora") or 
             (ansible_distribution == "RedHat") or
             (ansible_distribution == "CentOS")

     - name: install system updates for ubuntu systems
       become: yes
       apt: upgrade=dist update_cache=yes
       when: (ansible_distribution == "Ubuntu") or 
             (ansible_distribution == "Debian")

     - name: install the latest ntp and other required dependencies for RHEL < 8
       become: yes
       package:
         name:
           - ntp
           - git
           - python2-pip
         state: latest
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version < "8") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version < "8")

     - name: install the latest ntp and other required dependencies for RHEL >= 8
       become: yes
       package:
         name:
           - chrony
           - git
           - python2-pip
         state: latest
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version > "7") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version > "7") or
             (ansible_distribution == "Fedora")

     - name: install the other required dependencies Ubuntu
       become: yes
       package:
         name: 
           - ntp
           - git
           - python-pip
         state: latest
       when: (ansible_distribution == "Ubuntu") or 
             (ansible_distribution == "Debian")

     - name: Upgrade PIP
       become: yes
       pip:
         name: pip
         state: latest

     - name: Install pexpect
       become: yes
       pip:
         name: pexpect

     - name: Stop ntpd
       become: yes
       service:
         name: ntpd
         state: stopped
       when: aac_base_tz is defined

     - name: Set timezone
       become: yes
       timezone:
         name: "{{ item }}"
         with_items:
           - "{{ aac_base_tz }}"
       when: aac_base_tz is defined

     - name: Enable ntpd
       become: yes
       service:
         name: ntpd
         enabled: yes
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version < "8") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version < "8") or
             (ansible_distribution == "Ubuntu") or 
             (ansible_distribution == "Debian")

     - name: Start ntpd
       become: yes
       service:
         name: ntpd
         state: started
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version < "8") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version < "8") or
             (ansible_distribution == "Ubuntu") or 
             (ansible_distribution == "Debian")

     - name: Enable chrony
       become: yes
       service:
         name: chrony
         enabled: yes
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version > "7") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version > "7") or
             (ansible_distribution == "Fedora")

     - name: Start chrony
       become: yes
       service:
         name: chrony
         state: started
       when: (ansible_distribution == "RedHat" and  ansible_distribution_major_version > "7") or
             (ansible_distribution == "CentOS" and ansible_distribution_major_version > "7") or
             (ansible_distribution == "Fedora")

     - name: Stop postfix
       become: yes
       service:
         name: postfix
         state: stopped
