---
# version: 1.0.0
- hosts: localhost
  gather_facts: true
  become_user: root

- name: TZ
  import_playbook: aac-base-tz.yaml

- name: SELinux
  import_playbook: aac-base-selinux.yaml

- hosts: localhost
  tasks:
     - name: install dcli
       become: yes
       pip:
         name: dcli

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
