---
# version: 1.0.1

- hosts: localhost
  gather_facts: true
  become_user: root

- name: TZ
  import_playbook: aac-base-tz.yaml

- name: SELinux
  import_playbook: aac-base-selinux.yaml

- hosts: localhost
  tasks:
     - name: No Debian Family Support Output
       debug:
         msg: "No Debian Family Support for Isolib, use RedHat-like OS"
       when: ansible_os_family == "Debian"

     - name: No Debian Family Support
       meta: end_host
       when: ansible_os_family == "Debian"

     - name: add Negativo17 GPG Keys
       become: yes
       rpm_key:
         state: present
         key: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
       when: ansible_os_family == "RedHat"

     - name: install Schilling Fedora Repo
       become: yes
       get_url:
         url: https://negativo17.org/repos/fedora-cdrtools.repo
         dest: /etc/yum.repos.d
       when: ansible_distribution == "Fedora"

     - name: install Schilling EPEL Repo
       become: yes
       get_url:
         url: https://negativo17.org/repos/epel-cdrtools.repo
         dest: /etc/yum.repos.d
       when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

     - name: install dependencies
       become: yes
       package:
         name:
           - dvd+rw-tools
           - udftools
           - cdrecord
           - mkisofs
           - cdda2wav
         state: latest
       when: ansible_os_family == "RedHat"

     - name: Create Bin Directory
       file:
         path: "{{ansible_user_dir}}/bin"
         mode: 0755
         state: directory
       ignore_errors: yes
       when: ansible_os_family == "RedHat"

     - name: Download the latest version of isolib.sh
       get_url:
         url: https://raw.githubusercontent.com/Texiwill/aac-lib/master/isolib/isolib.sh
         dest: "{{ansible_user_dir}}/bin"
         mode: 0755
       when: ansible_os_family == "RedHat"

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
