---
# version: 1.0.0

- hosts: localhost
  gather_facts: true
  become_user: root
  tasks:
     - name: add RPMFusion Free GPG Keys
       become: yes
       rpm_key:
         state: present
         key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

     - name: add RPMFusion nonfree GPG Keys
       become: yes
       rpm_key:
         state: present
         key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

     - name: add Remi GPG Keys
       become: yes
       rpm_key:
         state: present
         key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2020

     - name: Set Facts
       set_fact:
         set_distro: el
         set_remi: enterprise
       when: ansible_distribution == "RedHat"

     - name: Set Facts
       set_fact:
         set_distro: fedora
         set_remi: fedora
       when: ansible_distribution == "Fedora"

     - name: add repos
       become: yes
       package:
         name:
           - "https://mirrors.rpmfusion.org/free/{{set_distro}}/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
           - "https://mirrors.rpmfusion.org/nonfree/{{set_distro}}/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
           - "https://rpms.remirepo.net/{{set_remi}}/remi-release-{{ansible_distribution_major_version}}.rpm"
         state: present
       when: ansible_os_family == "RedHat"

     - name: Download Skype Repo
       become: yes
       get_url:
         url: "https://repo.skype.com/rpm/stable/skype-stable.repo"
         dest: "/etc/yum.repos.d/skype-stable.repo"
         mode: 0644
       when: ansible_os_family == "RedHat"

     - name: enable jdoss slack repo
       become: yes
       command: 
         cmd: dnf copr enable -y jdoss/slack-repo
         creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:jdoss:slack-repo.repo
       when: ansible_distribution == "Fedora"

     - name: install slack-repo
       become: yes
       package:
         name: 
           - slack-repo
         state: latest
       when: ansible_distribution == "Fedora"

     - name: Get Nvidia PCI BusID
       become: no
       shell: "/usr/sbin/lspci |/usr/bin/grep NVIDIA|/usr/bin/grep VGA|/usr/bin/awk '{print $1}'|/usr/bin/sed 's/0\\([0-9]\\):0\\([0-9]\\)\\.\\([0-9]\\)/PCI:\\1:\\2:\\3/'"
       register: pci_busid

     - name: Save X.org Conf file
       become: yes
       copy:
         src: /etc/X11/xorg.conf
         dest: /etc/X11/xorg.conf.olde
         mode: '0644'

     - name: Write X.org Conf file
       become: yes
       blockinfile:
         path: /etc/X11/xorg.conf
         block: |
           # nvidia-xconfig: X configuration file generated by nvidia-xconfig
           # nvidia-xconfig:  version 450.80.02
           
           Section "ServerLayout"
               Identifier     "Layout0"
               Screen      0  "Screen0" 0 0
               InputDevice    "Keyboard0" "CoreKeyboard"
               InputDevice    "Mouse0" "CorePointer"
               Option         "Xinerama" "0"
           EndSection
           
           Section "Files"
               FontPath        "/usr/share/fonts/default/Type1"
           EndSection
           
           Section "InputDevice"
               # generated from default
               Identifier     "Mouse0"
               Driver         "evdev"
               Option         "Protocol" "auto"
               Option         "Device" "/dev/input/mice"
               Option         "Emulate3Buttons" "no"
               Option         "ZAxisMapping" "4 5"
           EndSection
           
           Section "InputDevice"
               # generated from default
               Identifier     "Keyboard0"
               Driver         "kbd"
           EndSection
           
           Section "Monitor"
               # HorizSync source: builtin, VertRefresh source: builtin
               Identifier     "Monitor0"
               VendorName     "Unknown"
               ModelName      "CRT-0"
               HorizSync       30.0 - 83.0
               VertRefresh     56.0 - 83.0
               Option         "DPMS"
               Option         "PreferredMode" "1920x1200"
           EndSection
           
           Section "Device"
               Identifier     "Device0"
               Driver         "nvidia"
               VendorName     "NVIDIA Corporation"
               BoardName      "Quadro K4000"
               BusID          "{{pci_busid.stdout}}"
               #Option         "NvAGP" "0"
               #Option         "RenderAccel" "true"
               Option         "UseEdidDpi" "FALSE"
               Option         "UseEdid" "FALSE"
               Option         "DPI" "96 x 96"
               #Option         "XAANoOffscreenPixmaps" "true"
               #Option         "DRI" "true"
               #Option         "HWcursor"
               #Option         "CursorShadow"
               #Option         "CursorShadowAlpha" "32"
               #Option         "CursorShadowXOffset" "2"
               #Option         "CursorShadowYOffset" "2"
               #Option         "AddARGBGLXVisuals" "true"
               #Option         "AllowGLXWithComposite" "true"
               #Option         "SoftwareRenderCacheSize" "0x800000"
               Option         "ConnectToAcpid" "off"
           EndSection
           
           Section "Screen"
               Identifier     "Screen0"
               Device         "Device0"
               Monitor        "Monitor0"
               DefaultDepth    24
               #Option         "NoVirtualSizeCheck"
               #Option         "DisableGLXRootClipping" "True"
               #Option         "RenderAccel" "True"
               #Option         "NoRenderExtension" "False"
               #Option         "AllowGLXWithComposite" "True"
               #Option         "UseEdidFreqs" "false"
               #Option         "AddARGBGLXVisuals" "True"
               #Option         "UseEdidDpi" "FALSE"
               #Option         "UseEdid" "FALSE"
               #Option         "CustmEDID" "GPU-0.CRT-0:/etc/X11/edid-asus.txt"
               Option         "ConnectedMonitor" "CRT-0"
               #Option         "Stereo" "0"
               #Option         "nvidiaXineramaInfoOrder" "CRT-0"
               #Option         "metamodes" "1920x1200_60.00 +0+0; 1920x1080_60.00 +0+0; 1280x1024 +0+0; 1024x768_60 +0+0; 800x600 +0+0; 640x480 +0+0; 1280x1024 +0+0"
               #Option         "SLI" "Off"
               #Option         "MultiGPU" "Off"
               #Option         "BaseMosaic" "off"
               SubSection     "Display"
                   Depth       24
               EndSubSection
           EndSection
         mode: 0644
         create: yes
        
     - name: install packages
       become: yes
       package:
         name: 
           - quiterss
           - skypeforlinux
           - pidgin
           - dropbox
           - nautilus-dropbox
           - remmina
           - nethack
           - slack
           - xorg-x11-drv-nvidia
           - vdpauinfo
           - libva-vdpau-driver
           - libva-utils
           - mesa-libGL
           - mesa-libEGL
           - libglvnd
           - nvidia-xconfig
           - nvidia-settings
           - nvidia-persistenced
           - google-chrome-stable
           - mediainfo
           - libmediainfo
           - "@Mate Desktop"
         state: latest
       when: ansible_os_family == "RedHat"

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
