---
# version: 1.0.3

- hosts: localhost
  gather_facts: true
  become_user: root

- name: TZ
  import_playbook: aac-base-tz.yaml

- name: SELinux
  import_playbook: aac-base-selinux.yaml

- hosts: localhost
  tasks:
     - name: install RHEL < 8 dependencies
       become: yes
       package:
         name:
           - wget
           - libxml2
           - perl-XML-Twig
           - ncurses
           - bc
           - jq
           - sharutils
           - python
           - python-urllib3
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version ("8","<")

     - name: Need Yum Utils
       become: yes
       package:
         name: yum-utils
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version ("7",">")

     - name: Need Power Tools for RHEL 8
       become: yes
       shell: "yum-config-manager --enable PowerTools"
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version ("7",">")

     - name: install the RHEL >= 8 dependencies
       become: yes
       package:
         name:
           - wget
           - libxml2
           - perl-XML-Twig
           - ncurses
           - bc
           - jq
           - sharutils
           - python2
           - python2-urllib3
         state: latest
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version ("7",">")

     - name: install the Debian dependencies for LinuxVSM
       become: yes
       package:
         name:
           - wget
           - libxml2
           - libxml2-utils
           - xml-twig-tools
           - ncurses-base
           - bc
           - jq
           - sharutils
           - python
           - python-urllib3
         state: latest
       when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version is version("20",'<')) or
             (ansible_distribution == "Debian")

     - name: install the Ubuntu dependency for LinuxVSM
       become: yes
       package:
         name:
           - wget
           - libxml2
           - libxml2-utils
           - xml-twig-tools
           - ncurses-base
           - bc
           - jq
           - sharutils
           - python
           - python3-urllib3
         state: latest
       when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version is version("20",'>='))

     - name: Install Xcode CLI for MacOSX
       ignore_errors: yes
       shell: "xcode-select --install"
       when: ansible_distribution == "MacOSX"

     - name: Install Dependencies for MacOSX
       homebrew:
         name:
           - gnu-sed
           - wget
           - jq
           - cpanminus
         state: latest
       when: ansible_distribution == "MacOSX"

     - name: Install MacOS Perl Dependencies
       cpanm:
         name: XML::Twig
       when: ansible_distribution == "MacOSX"

     - name: create bin directory
       file:
         path: "{{ansible_user_dir}}/bin"
         state: directory
       when: ansible_distribution == "MacOSX"

     - name: Set MacOSX Facts
       set_fact:
         path_two: 
           - "{{ansible_user_dir}}/perl5/bin"
           - "{{ansible_user_dir}}/bin"
       when: ansible_distribution == "MacOSX"

     - name: Merge the LinuxVSM MacOSX Paths
       set_fact:
         vsmpath: "{{(mypath + path_two)|unique}}"
       when: ansible_distribution == "MacOSX"

     - name: Update .zshrc on MacOSX
       lineinfile:
         path: "{{ansible_user_dir}}/.zshrc"
         regexp: 'PATH='
         line: "export PATH=$PATH{{vsmpath|join(':')}}"
         create: yes
       when: ansible_distribution == "MacOSX"

     - name: Update .bash_profile on MacOSX
       lineinfile:
         path: "{{ansible_user_dir}}/.bash_profile"
         regexp: 'PATH='
         line: "export PATH=$PATH{{vsmpath|join(':')}}"
         create: yes
       when: ansible_distribution == "MacOSX"

     - name: Download the latest version of LinuxVSM
       become: yes
       get_url:
         url: https://raw.githubusercontent.com/Texiwill/aac-lib/master/vsm/vsm.sh
         dest: /usr/local/bin
         mode: 0755
       when: ansible_distribution != "MacOSX"

     - name: Download the latest version of LinuxVSM MacOSX
       get_url:
         url: https://raw.githubusercontent.com/Texiwill/aac-lib/master/vsm/vsm.sh
         dest: "{{ansible_user_dir}}/bin"
         mode: 0755
       when: ansible_distribution == "MacOSX"

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
