---
# version: 1.0.1

- hosts: localhost
  become_user: root

- name: VSM
  import_playbook: LinuxVSM.yaml

- hosts: localhost
  tasks:
     - name: install RHEL development tools
       become: yes
       package:
         name:
           - gcc
           - cpp
           - libmpc
           - mpfr
           - perl-YAML
           - libuuid-devel
           - perl-Module-Build
           - perl-CPAN
         state: latest
       when: ansible_os_family == "RedHat"

     - name: install DEBIAN development tools
       become: yes
       package:
         name:
           - gcc
           - cpp
           - libmpc-dev
           - libmpfr-dev
           - libyaml-perl
           - libuuid-perl
           - libmodule-build-perl
         state: latest
       when: ansible_os_family == "Debian"

     - name: install the latest version of vCLI dependencies for RedHat
       become: yes
       package:
         name:
           - openssl-devel
           - perl-Archive-Zip
           - perl-Class-Data-Inheritable
           - perl-Class-MethodMaker
           - perl-Compress-Raw-Zlib
           - perl-Compress-Zlib
           - perl-Convert-ASN1
           - perl-Crypt-OpenSSL-RSA
           - perl-Crypt-SSLeay
           - perl-Crypt-OpenSSL-X509
           - perl-Data-Dump
           - perl-Data-Dumper
           - perl-HTML-Parser
           - perl-IO-Compress
           - perl-IO-Compress
           - perl-URI
           - uuid-perl
           - perl-XML-NamespaceSupport
           - perl-XML-LibXML
           - perl-Socket6
           - perl-Text-Template
           - perl-Time-Piece
           - perl-Path-Class
           - perl-LWP-Protocol-https
           - perl-IO-Socket-INET6
           - perl-Net-INET6Glue
           - perl-Try-Tiny
         state: latest
       when: ansible_os_family == "RedHat"

     - name: install the latest version of vCLI dependencies for Debian
       become: yes
       package:
         name:
           - libssl-dev
           - libarchive-zip-perl
           - libclass-data-inheritable-perl
           - libclass-methodmaker-perl
           - libcompress-raw-zlib-perl
           - libperl-dev
           - libconvert-asn1-perl
           - libcrypt-openssl-rsa-perl
           - libcrypt-openssl-x509-perl
           - libdata-dump-perl
           - libhtml-parser-perl
           - liburi-perl
           - libuuid-perl
           - libxml-namespacesupport-perl
           - libxml-libxml-perl
           - libsocket6-perl
           - libcrypt-ssleay-perl
       when: ansible_os_family == "Debian"

     - name: Check if Credential exists
       stat:
         path: "/tmp/vsm.{{ ansible_env.USER }}/.credstore"
       register: stat_result

     - name: Check if vCLI exists
       stat:
         path: "/usr/bin/vmware-uninstall-vSphere-CLI.pl"
       register: stat_cli_result

     - name: Download the latest version of vCLI
       become: no
       shell: "/usr/local/bin/vsm.sh -y -f --dlg CLI.*.x86_64.tar.gz | grep Local"
       args:
         executable: /bin/bash
       register: vsm_local

     - name: Get Local Filename
       set_fact:
         file_local: "{{ vsm_local.stdout | regex_replace('^Local:(..)','\\1') }}"

     - name: Debug
       debug:
         msg: "Installing {{file_local}}"

     - name: Unbundle
       unarchive:
         src: "{{ file_local }}"
         dest: /tmp

     - name: Uninstall older vCLI
       become: yes
       shell: "/usr/bin/vmware-uninstall-vSphere-CLI.pl"
       args:
         executable: /bin/bash
       when: stat_cli_result.stat.exists

     - name: Update installed_ssl_version in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .installed_ssl_version =' 
         line: "   my $installed_ssl_version = '1.0.0';"
       when: ansible_os_family == "Debian"

     - name: Update ssleay_installed in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .ssleay_installed = 0'
         line: '   my $ssleay_installed = 1;'
       when: ansible_os_family == "Debian"

     - name: Update OpenSSL_installed in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .OpenSSL_installed = 0'
         line: '   my $OpenSSL_installed = 1;'
       when: ansible_os_family == "Debian"

     - name: Update LibXML2_installed in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .LibXML2_installed = 0'
         line: '   my $LibXML2_installed = 1;'
       when: ansible_os_family == "Debian"

     - name: Update OpenSSL_dev_installed in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .OpenSSL_dev_installed = 0'
         line: '   my $OpenSSL_dev_installed = 1;'
       when: ansible_os_family == "Debian"

     - name: Update e2fsprogs_installed in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .e2fsprogs_installed = 0'
         line: '   my $e2fsprogs_installed = 1;'
       when: ansible_os_family == "Debian"

     - name: Update e2fsprogs_version in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: "my .e2fsprogs_version = '0'"
         line: "   my $e2fsprogs_version = '1.42';"
       when: ansible_os_family == "Debian"

     - name: Update install_rhel55_local in vmware_install.pl for Debian/Ubuntu
       lineinfile:
         path: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         regexp: 'my .install_rhel55_local = 0'
         line: '   my $install_rhel55_local = 1;'
       when: ansible_os_family == "Debian"

     - name: Install vCLI
       become: yes
       expect:
         command: /tmp/vmware-vsphere-cli-distrib/vmware-install.pl
         responses:
           'Press enter to display it.': 'n'
           '.*--More--.*': 'q'
           'Do you accept.*': 'yes'
           '[yes]': 'yes'
           '[/usr/bin]': '/usr/bin'

     - name: uninstall RHEL development tools
       become: yes
       package:
         name:
           - gcc
           - cpp
           - libmpc
           - mpfr
           - perl-YAML
           - libuuid-devel
           - perl-Module-Build
           - perl-CPAN
         state: absent
       when: ansible_os_family == "RedHat"

     - name: uninstall Debian development tools
       become: yes
       package:
         name:
           - gcc
           - cpp
           - libmpc-dev
           - libmpfr-dev
           - libyaml-perl
           - libuuid-perl
           - libmodule-build-perl
         state: absent
       when: ansible_os_family == "Debian"

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
