---
# version: 1.0.1

- hosts: localhost
  gather_facts: true
  become_user: root

- name: TZ
  import_playbook: aac-base-tz.yaml

- name: SELinux
  import_playbook: aac-base-selinux.yaml

- hosts: localhost
  tasks:
     - name: golang RPM Key
       become: yes
       rpm_key:
         state: present
         key: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO
       when: ansible_os_family == "RedHat"

     - name: golang repo
       become: yes
       get_url:
         url: https://mirror.go-repo.io/centos/go-repo.repo
         dest: /etc/yum.repos.d
         mode: 0644
       when: ansible_os_family == "RedHat"

     - name: install golang
       become: yes
       package:
         name:
           - golang
         state: latest
       when: ansible_distribution != "MacOSX"

     - name: Install Dependencies for MacOSX
       homebrew:
         name:
           - golang
         state: latest
       when: ansible_distribution == "MacOSX"

     - name: Getting vctui
       become: no
       shell: "go get -u github.com/thebsdbox/vctui"
       args:
         executable: /bin/bash

     - name: Create bin diretory
       file:
         path: "{{ansible_env.HOME}}/bin"
         state: directory
         mode: 0755

     - name: Install vctui
       copy: 
         src: "{{ansible_env.HOME}}/go/bin/vctui"
         dest: "{{ansible_env.HOME}}/bin/vctui"
         mode: 0755

- name: Fix SELinux
  import_playbook: aac-base-fixselinux.yaml
...
